[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ecs"
crate-type = ["cdylib"]

[dependencies]
bevy_ecs = "0.15.1"
pyo3 = "0.23.3"
